inputs:
  ref_prompt:  "A `dog , a `cat and a `dog near a grass."
  base_prompt: "A `dog , a `cat and a `dog near a forest."
  negative_prompt: ""
  custom_prompts:
    - "A <dog> `<dog_2> , a <dog> `<dog_2>  and a dog> `<dog_2> near a forest."
    - "A <pet_cat1> `<pet_cat1_2>, a <pet_cat1> `<pet_cat1_2> and a <pet_cat1> `<pet_cat1_2> near a forest."
    - "A <dog6> `<dog6_2>, a <dog6> `<dog6_2> and a <dog6> `<dog6_2> near a forest."
  ref_image_path: "sample/ref_image/prompt2/prompt2.png"
  ref_mask_paths:
    - "sample/ref_image/prompt2/ldog.png"
    - "sample/ref_image/prompt2/mcat.png"  
    - "sample/ref_image/prompt2/rdog.png"  
  init_mask_from_points: False
  mask_center_points: 
    - [350, 200]
    - [150, 300]
  init_image_path: ~
  init_mask_path: ~       
  edlora_paths:
    - "inf/8EDLoRA_corgi/models/edlora_model-latest.pth"  
    - "inf/8EDLoRA_pet_cat1/models/edlora_model-latest.pth"
    - "inf/8EDLoRA_uglycorgi/models/edlora_model-latest.pth"
  load_edlora: True
  lora_alpha: 0.95

outputs:
  outroot: "outputs/prompt2"
  image_outdir: "inference_results"
  latents_outdir: "inverted_latents"
  self_attn_outdir: "self_attn"
  cross_attn_outdir: "cross_attn"
  feature_mask_outdir: "feature_mask"


base_model:
  sd_ckpt: "experiments/pretrained_models/chilloutmix"
  variant: ""

sd_t2i:
  height: 512
  width: 512
  guidance_scale: 7.5
  num_inference_steps: 300
  start_seed: 0
  batch_size: 10
  n_batches: 1
  verbose: False

attention_operations:
  attn_guidance_end: 60
  attn_guidance_interval: 1
  attn_guidance_weight: 10
  custom_attn_guidance_factor: 1.0

  processor_filter_guidance: '.*up_blocks\.1\.attentions\.0.*attn1.*'
  params_guidance: ["key"]
  processor_filter_mask: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_mask: ['attention_probs']
  processor_filter_merge: '.*up_blocks.*'
  params_merge: ["feature_output"]
  processor_filter_view_sa: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_view_sa: ["attention_probs"]      
  processor_filter_view_ca: '.*up_blocks\.2\.attentions\.1.*attn2.*'
  params_view_ca: ["attention_probs"]    

  mask_refinement_start: 50
  mask_refinement_end: 80
  mask_update_interval: 5
  mask_overlap_threshold: 0
  num_kmeans_init: 100
  rect_mask: False

  use_loss_mask: False
  visualization: False



